const userMessage = [
  ["what is kiboto", "what is kes" , "what is kesltd", "KES"],
  ["<?php include_once('./database/connect.php'); $sql50 = 'SELECT DISTINCT category FROM chat_question'; $query50 = mysqli_query($con, $sql50); echo '<p>Select questions you wish to ask based on technology:<hr><ul>'; while($row50 = mysqli_fetch_array($query50)){ echo \"<li style='text-align: left'><a href='#'>\".$row50['category'].\"</a></li>\"; }echo '</ul></p>'; ?>"],
  ["Go", "go", "GO"],
  ["what services does kiboto engineering solutions limited provide"],
  ["100"],
  ["101"],

  ["muraho", "mwiriwe", "mwiriweho", "mukomere cyane"],
  ["bite", "bite?", "bite ?", "bite c", "bitex", "bite x", "bite se", "bite byawe"],
  ["amakuru", "makuru ki", "makuru ki?", "mumeze mute", "bite"],
  ["how do i get a quote"],
  ["what is the typical project duration"],
  ["do you work with private clients"],
  ["what types of projects do you handle"],
  ["hi", "hey", "hello"],
  ["sure", "yes", "no"],
  ["are you genious", "are you nerd", "are you intelligent"],
  ["i hate you", "i dont like you"],
  ["how are you", "how is life", "how are things", "how are you doing"],
  ["how is corona", "how is covid 19", "how is covid19 situation"],
  ["what are you doing", "what is going on", "what is up"],
  ["how old are you"],
  ["who are you", "are you human", "are you bot", "are you human or bot"],
  ["who created you", "who made you", "who is your creator"],
  ["your name please","your name", "may i know your name", "what is your name", "what call yourself",],
  ["i love you"],
  ["happy", "good", "fun", "wonderful", "fantastic", "cool", "very good"],
  ["bad", "bored", "tired"],
  ["help me", "tell me story", "tell me joke", "make me laugh"],
  ["ah", "ok", "okay", "nice", "welcome"],
  ["thanks", "thank you", "thank you very much"],
  ["what should i eat today"],
  ["bro"],
  ["what", "why", "how", "where", "when"],
  ["corona", "covid19", "coronavirus"],
  ["you are funny"],
  ["i dont know"],
  ["boring", "bored asf"],
  ["im tired"],
  ["how can i contact kiboto engineering solutions limited"],
  ["can you provide more details about your building and consultation services"],
  ["what types of road and bridge construction projects does kiboto handle"],
  ["what expertise does kiboto have in water supply systems"],
  ["how does kiboto handle wastewater management projects"],
  ["what does kiboto offer in terms of irrigation and marshland development"],
  ["could you explain kiboto's approach to dam construction"],
  ["how does kiboto ensure quality in its construction projects"],
  ["does kiboto Engineering Solutions Limited offer consultancy services"],
  ["what geographical areas does kiboto engineering solutions limited serve"],
  ["how does kiboto handle project timelines and deadlines"],
  ["can i see examples of projects completed by kiboto engineering solutions limited"],
  ["how does kiboto ensure environmental sustainability in its projects"],
  ["is kiboto engineering solutions limited involved in community development projects"],
  ["what are the main sectors kiboto engineering solutions operates in"],
  ["how can kiboto assist with infrastructure development"],
  ["does kiboto provide maintenance services for completed projects"],
  ["what types of clients does kiboto work with"],
  ["how does kiboto ensure safety on its construction sites"],
  ["can kiboto handle both large and smallscale projects"],
  ["what is kiboto approach to cost estimation for projects"],
  ["how can i request a consultation with kiboto"],
  ["is kiboto involved in sustainable construction practices"],
  ["can kiboto assist with regulatory approvals and permits"],
  ["how does kiboto ensure quality control in construction"],
  ["does kiboto offer customized solutions for unique project requirements"],
  ["what is kiboto experience in international projects"],
  ["how does kiboto contribute to local communities"],
  ["does kiboto provide postproject support and followup"],
  ["does kiboto engineering solutions provide project management services"],
  ["is kiboto involved in road construction projects"],
  ["can kiboto assist with water supply system design"],
  ["does kiboto offer consultancy services in engineering"],
  ["does kiboto operate in musanze, rwanda"],
  ["does kiboto provide maintenance services for completed projects"],
  ["does kiboto have experience in dam construction"],
  ["can kiboto handle largescale infrastructure projects"],
  ["does kiboto prioritize environmental sustainability in its projects"],
  ["can kiboto assist with obtaining regulatory approvals for projects"],
  ["does kiboto offer services in building and construction"],
  ["is kiboto involved in irrigation and marshland development"],
  ["can kiboto provide examples of past projects"],
  ["does kiboto provide design services for infrastructure projects"],
  ["is kiboto available for consultations on engineering projects"],
  ["does kiboto have expertise in wastewater management"],
  ["can kiboto assist with road and bridge construction projects"],
  ["does kiboto collaborate with local communities on projects"],
  ["can kiboto provide cost estimates for projects"],
  ["does kiboto ensure safety standards on construction sites"], 
];

const botReply = [
  ["Kiboto Engineering Solutions"],
  ["How is the situation going."],
  ["<p class='inchat-p'>Choose a number that corresponds with option below:<p><ul class='inchat-ul'><li>100. Our Services</li><li>101. Contact Us</li><ul>"],
  ["<p class='inchat-p'>KIBOTO Engineering Solutions Limited provides a range of services including:</p><ul class='inchat-ul'><li>Projects in building, consultation, and supervision</li><li>Road and bridge construction</li><li>Water supply systems</li><li>Wastewater management</li><li>Irrigation and marshland development</li><li>Dams construction</li></ul>"],
  ["<p class='inchat-p'>KIBOTO Engineering Solutions Limited provides a range of services including:</p><ul class='inchat-ul'><li>Projects in building, consultation, and supervision</li><li>Road and bridge construction</li><li>Water supply systems</li><li>Wastewater management</li><li>Irrigation and marshland development</li><li>Dams construction</li></ul>"],
  ["Contact us by using this info:<hr><b>Website:</b>: www.kesltd<br><b>E-mail:</b>(fsternkiboto@gmail.com)<br><b>Phone Number:</b>(+250788334864 / +250784742541)<br> Or visit <a href='contact.php'>this page</a>."],

  ["Twiriwe neza", "Amakuru yanyu?", "Mwiriweho, Mumeze mute?"],
  ["Ni byiza", "Ni sawa", "Ni neza", "Ni byiza. Woe?"],
  ["Amakuru ni meza", "Tumeze neza", "Nimeza. Naho mwebwe?", "Ni meza, Turashima umuremyi"],
  ["You can request a quote by contacting us through our website or email."],
  ["Project duration varies based on scope. We will provide an estimate during the consultation."],
  ["Yes, we serve both public and private sectors."],
  ["We handle various projects including building, road and bridge construction, and more."],
  ["Hello!", "Hi!", "Hey!", "Hi there!"],
  ["Okay"],
  ["Yes I am! ", "Yeah!"],
  ["I'm sorry about that. But I like you dude."],
  ["Fine... how are you?", "Pretty well, how are you?", "Fantastic, how are you?",],
  ["Getting better. There?", "Somewhat okay!", "Yeah fine. Better stay home!"],
  ["Nothing much", "About to go to sleep", "Can you guess?", "I don't know actually",],
  ["I am always young."],
  ["I am just a bot", "I am a bot. What are you?"],
  ["Kiboto Ltd", "Joseph"],
  ["I am nameless", "I don't have a name"],
  ["I love you too", "Me too"],
  ["Have you ever felt bad?", "Glad to hear it"],
  ["Why sure?", "Why1? You shouldn't!", "Try watching TV", "Chat with me."],
  ["What about?", "Once upon a time..."],
  ["Tell me a story", "Tell me a joke", "Tell me about yourself"],
  ["You're welcome"],
  ["Potato", "Hamburger", "Burger", "So", "Pizza"],
  ["Dude!"],
  ["Yes?"],
  ["Please stay home"],
  ["Glad to hear it"],
  ["Say something interesting"],
  ["Sorry for that. Let's chat!"],
  ["Take some rest, Dude!"],
  ["You can contact us through our website, phone number, or visit our office in Musanze, Rwanda."],
  ["Our building and consultation services cover architectural design, project planning, and construction management. We ensure high-quality standards and timely completion of projects."],
  ["We specialize in road construction, including highways and urban roads, as well as bridge construction for various spans and purposes."],
  ["We design and implement water supply systems tailored to client needs, ensuring sustainable and efficient water distribution."],
  ["Our wastewater management services include treatment plant design, construction, and maintenance, ensuring environmental compliance and sustainability."],
  ["We provide expertise in designing and implementing irrigation systems for agriculture and development of marshlands for ecological and agricultural purposes."],
  ["Our dam construction services encompass planning, design, and construction management to support water resource management and hydroelectric power generation."],
  ["We adhere to rigorous quality control measures throughout every phase of the project, from planning to completion, to ensure durability and client satisfaction."],
  ["Yes, we provide consultancy services in engineering, construction, and project management to assist clients in optimizing project outcomes and reducing risks."],
  ["We primarily serve clients in Musanze, Rwanda, and surrounding regions, but we are open to discussing projects in other areas as well."],
  ["We meticulously plan each project and adhere to strict timelines to ensure projects are completed on schedule without compromising quality."],
  ["Yes, you can view our portfolio of past projects on our website or request more information during a consultation."],
  ["We integrate sustainable practices into our project designs and construction processes to minimize environmental impact and promote eco-friendly solutions."],
  ["Yes, we actively participate in community development initiatives through infrastructure projects that benefit local communities."],
  ["KIBOTO operates primarily in construction, engineering consultancy, and project management."],
  ["We offer expertise in designing and building infrastructure such as roads, bridges, water supply systems, and dams."],
  ["Yes, we offer comprehensive maintenance services to ensure long-term functionality and efficiency of our projects."],
  ["We serve a diverse range of clients including government agencies, private companies, and NGOs."],
  ["Safety is our priority. We adhere strictly to safety regulations and provide continuous training to our staff."],
  ["Yes, we have experience in managing projects of various scales, from small-scale developments to large infrastructure projects."],
  ["We provide detailed cost estimates based on project requirements, ensuring transparency and accuracy."],
  ["You can request a consultation through our website or by contacting our office directly."],
  ["Yes, we integrate sustainable materials and practices to minimize environmental impact in our projects."],
  ["Yes, we assist clients in navigating regulatory processes and obtaining necessary approvals for their projects."],
  ["We have stringent quality control measures in place, including regular inspections and testing, to ensure high standards."],
  ["Yes, we tailor our services to meet specific project needs and objectives."],
  ["We have successfully completed projects both locally and internationally, bringing our expertise to diverse environments."],
  ["We contribute to community development through job creation, skills training, and infrastructure improvements."],
  ["Yes, we provide ongoing support after project completion to address any client needs or concerns."],
  ["Yes, we offer project management services."],
  ["Yes, we specialize in road construction projects."],
  ["Yes, we provide water supply system design services."],
  ["Yes, we provide consultancy services in engineering."],
  ["Yes, we are located in Musanze, Rwanda."],
  ["Yes, we offer maintenance services for completed projects."],
  ["Yes, we have experience in dam construction."],
  ["Yes, we have experience in managing large-scale infrastructure projects."],
  ["Yes, we prioritize environmental sustainability in our projects."],
  ["Yes, we assist with obtaining regulatory approvals for projects."],
  ["Yes, we offer building and construction services."],
  ["Yes, we specialize in irrigation and marshland development."],
  ["Yes, we can provide examples of past projects."],
  ["Yes, we provide design services for infrastructure projects."],
  ["Yes, we offer consultations on engineering projects."],
  ["Yes, we have expertise in wastewater management."],
  ["Yes, we specialize in road and bridge construction projects."],
  ["Yes, we collaborate with local communities on projects."],
  ["Yes, we can provide cost estimates for projects."],
  ["Yes, we ensure safety standards on construction sites."],
];

const alternative = [
  "Misunderstood: Contact us on (www.kesltd.rw), Email(fsternkiboto@gmail.com) Tel.No(+250788334864 / +250 784742541)<a href='#'>Otherwise, Visit this page</a>",
  "Oops, We do not quite get you well", 
  "Ask something else..."
]
